services:
  rocky:
    build: .
    container_name: attacklab
    ports:
      - "15513:15513"
      - "15514:15514"
    volumes:
      - .:/attacklab
    working_dir: /attacklab
    command: sh -c "make cleanallfiles && make start && tail -f /dev/null"
